server:
  port: 8084
spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/jabak_lah_db
    username: root
    password: ENSA2023
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
vonage:
  apiKey: b3dbcd2e
  apiSecret: Ubpj4RKEvVluJ3iL